/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "task.h"
#include "portmacro.h"


TaskHandle_t canTaskHandle;
TaskHandle_t flashTaskHandle;

int taskInit(void)
{
	if(pdPASS != xTaskCreate(canTask,"canTask",128,NULL,2,canTaskHandle))
	{
		return -1;
	}
	if(pdPASS != xTaskCreate(flashTask,"flashTask",128,NULL,2,flashTaskHandle))
	{
		return -1;
	}

	return 0;
}
int main(void)
{
    /* Loop forever */
	if(taskInit() == 0)
	{
		vTaskStartScheduler();
	}
	for(;;)
	{
		;
	}
}

void canTask(void* parm)
{
	(void*)parm;
	while(1)
	{

		vTaksDelay(pdMS_TO_TICKS(20));
	}
}

void flashTask(void* parm)
{
	(void*)parm;
	while(1)
	{

		vTaksDelay(pdMS_TO_TICKS(20));
	}
}
