/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "timer.h"
uint8_t flag = 0;
uint16_t cntVal = 0;

int main(void)
{
    /* Loop forever */
	clock_init();
	gpio_init();
	timer6_init();
	for(;;);
}

void TIM6_DAC_IRQHandler(void)
{
	if(flag)
	{
		set();
	}
	else
	{
		clear();
	}
	cntVal = getCNTval();

	flag = !flag;
}
