/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "timer.h"
uint8_t flag = 0;
uint16_t cntVal = 0;


#include "stm32_f429xx.h"

void spi_peripheral_clock_init();
void spi_gpio_init();
void spi_init(void);
void spi_send(uint8_t data);

void adc_gpio_init(void)
{
    // 1. Enable GPIOA clock
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    // 2. Set PA0 to analog mode
    GPIOA->MODER |= (3 << (0 * 2));  // MODER0 = 11 => analog
    GPIOA->PUPDR &= ~(3 << (0 * 2)); // No pull-up/pull-down

    GPIOA->MODER |= (3 << (1 * 2));  // MODER0 = 11 => analog
    GPIOA->PUPDR &= ~(3 << (1 * 2)); // No pull-up/pull-down
}

void adc1_init(void)
{
    // 3. Enable ADC1 clock
    RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;

    // 4. ADC prescaler = divide by 8 (for APB2 clock up to 84 MHz)
    ADC->CCR |= (3 << 16); // ADC prescaler = PCLK2 / 8

    //ADC1->CR1 = ADC_CR1_SCAN;

    // 5. Set resolution to 12-bit
    ADC1->CR1 &= ~(3 << 24); // RES = 00 => 12-bit

    // 6. Set sampling time for channel 0
    ADC1->SMPR2 |= (7 << 0); // SMP0 = 111 => 480 cycles

    // 6. Set sampling time for channel 1
    //ADC1->SMPR2 |= (7 << 3); // SMP0 = 111 => 480 cycles

    // 7. Select channel 0 as first in regular sequence
    ADC1->SQR3 &= ~ADC_SQR3_SQ1; // Channel 0 is SQ1
//    ADC1->SQR1 = (1U << 20);
//    ADC1->SQR3 = (0U << 0) | (1U << 5);

    // 8. Enable ADC
    ADC1->CR2 |= ADC_CR2_ADON;
}

uint16_t adc1_read(void)
{
    // 9. Start conversion
    ADC1->CR2 |= ADC_CR2_SWSTART;

    // 10. Wait for conversion to complete
    while (!(ADC1->SR & ADC_SR_EOC));

    // 11. Read result
    return (uint16_t)(ADC1->DR);
}

void adc2_init(void)
{
    // 1. Enable clocks for GPIOA and ADC2
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;    // Enable GPIOA clock
    RCC->APB2ENR |= RCC_APB2ENR_ADC2EN;     // Enable ADC2 clock

    // 2. Configure PA1 as analog
    GPIOA->MODER |= (3U << (1 * 2));        // PA1 -> Analog mode (11)
    GPIOA->PUPDR &= ~(3U << (1 * 2));       // No pull-up/pull-down

    // 3. ADC Common Control Register (independent mode)
    ADC->CCR &= ~ADC_CCR_MULTI;             // Set ADCs to independent mode

    // 4. ADC2 configuration
    ADC2->CR1 = 0;                          // 12-bit resolution, no scan
    ADC2->CR2 = 0;                          // Right alignment, software trigger
    ADC2->SQR1 = 0;                         // 1 conversion in regular sequence
    ADC2->SQR3 = 1;                         // 1st conversion: channel 1 (IN1)

    // 5. Set sampling time for channel 1
    ADC2->SMPR2 |= (3U << (3 * 1));         // Channel 1: 56 cycles

    // 6. Enable ADC2
    ADC2->CR2 |= ADC_CR2_ADON;
}

uint16_t adc2_read(void)
{
    // 9. Start conversion
	 ADC2->CR2 |= ADC_CR2_SWSTART;              // Start conversion
	 while (!(ADC2->SR & ADC_SR_EOC));          // Wait until EOC is set
	 return (uint16_t)(ADC2->DR);
}

void delay(void)
{
	for(int i = 0; i < 99999;i++);
}

double auxBATvoltage = 0.0f;
double LDObattVoltage = 0.0f;

uint32_t value1 = 0;
uint32_t value2 = 0;

int main(void)
{
    /* Loop forever */
	clock_init();
	gpio_init();
    adc_gpio_init();
    //spi_gpio_init();
    //spi_peripheral_clock_init();
    adc1_init();
    adc2_init();
    //spi_init();

    while (1)
    {
        // Now value contains 12-bit ADC data from PA0 (0–4095)
    	value1 = adc1_read();
    	auxBATvoltage = (double)value1;
    	auxBATvoltage = (double)(auxBATvoltage / 4096) * 3.3; //PA0
        delay();
        value2 = adc2_read();
        LDObattVoltage = (double)value2;
        LDObattVoltage = (float)(LDObattVoltage / 4096) * 3.3; //PA1
        delay();

        if(auxBATvoltage > 2.9f)
        {
        	clear(D0_48V_PIN);
        	delay();
        	clear(D1_12V_PIN);
        }

        if(LDObattVoltage < 2.6f)
        {
        	set(D0_48V_PIN);
        	set(D1_12V_PIN);
        }
    }

   /* PA0 -> AUX battery volatge
	PA1 -> LDO voltage

	PG13 -> 48V
	PG14 -> 12V*/
}

void TIM6_DAC_IRQHandler(void)
{
	cntVal = getCNTval();

	flag = !flag;
}
